# Generated by Django 5.2.9 on 2025-12-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64, unique=True)),
                ('raw_json', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64, unique=True)),
                ('product_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('aio', 'All-in-One'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('brand', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=256)),
                ('os', models.CharField(blank=True, max_length=128)),
                ('cpu', models.CharField(blank=True, max_length=256)),
                ('gpu', models.CharField(blank=True, max_length=256)),
                ('ram_gb', models.IntegerField(blank=True, null=True)),
                ('storage_gb', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('display_inch', models.FloatField(blank=True, null=True)),
                ('price_text', models.CharField(blank=True, max_length=256)),
                ('battery_wh', models.FloatField(blank=True, null=True)),
                ('charging_power_w', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64, unique=True)),
                ('brand', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=256)),
                ('version', models.CharField(blank=True, max_length=128)),
                ('thumbnail', models.URLField(blank=True)),
                ('release_date', models.CharField(blank=True, max_length=32)),
                ('image', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
