# Generated by Django 5.2.6 on 2025-12-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productdetailraw_productdetailspec_productsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailspec',
            name='product_type',
        ),
        migrations.AddField(
            model_name='productdetailspec',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productdetailspec',
            name='release_date',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='productdetailspec',
            name='version',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='productdetailspec',
            name='brand',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productdetailspec',
            name='cpu',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='productdetailspec',
            name='gpu',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='productdetailspec',
            name='model',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productdetailspec',
            name='os',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='productdetailspec',
            name='price_text',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
