# Generated by Django 5.2.6 on 2025-12-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productdetailspec_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailspec',
            name='product_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('allinone', 'All-in-one'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
    ]
