# Generated by Django 5.2.6 on 2025-12-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('generation', models.CharField(max_length=100)),
                ('core', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('ssd', models.IntegerField()),
                ('display_size', models.FloatField(default=0.0)),
                ('resolution_x', models.IntegerField(default=0)),
                ('resolution_y', models.IntegerField(default=0)),
                ('graphics', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=50)),
                ('warranty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
