# Generated by Django 5.2.4 on 2025-12-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techspecs_id', models.CharField(max_length=64, unique=True)),
                ('english_id', models.CharField(blank=True, max_length=64, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_1', models.URLField(blank=True, null=True)),
                ('thumbnail_2', models.URLField(blank=True, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cpu_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_family', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('cpu_base_freq', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_boost_freq', models.CharField(blank=True, max_length=50, null=True)),
                ('igpu', models.CharField(blank=True, max_length=255, null=True)),
                ('dgpu', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_size', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_clock', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_max', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_slots', models.IntegerField(blank=True, null=True)),
                ('storage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ssd_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('hdd_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('display_diagonal', models.CharField(blank=True, max_length=50, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('display_panel', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('bluetooth_version', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('usb_c', models.IntegerField(blank=True, null=True)),
                ('usb_a_gen2', models.IntegerField(blank=True, null=True)),
                ('usb_a_gen1', models.IntegerField(blank=True, null=True)),
                ('hdmi_ports', models.IntegerField(blank=True, null=True)),
                ('dp_ports', models.IntegerField(blank=True, null=True)),
                ('ethernet_ports', models.IntegerField(blank=True, null=True)),
                ('raw_search', models.JSONField(blank=True, null=True)),
                ('raw_detail', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
