# Generated by Django 5.2.6 on 2025-12-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('notice', '공지'), ('tip', '개발팁'), ('qna', 'Q&A'), ('free', '자유게시판'), ('estimate', '견적 요청')], default='free', max_length=10, verbose_name='카테고리'),
        ),
    ]
