# Generated by Django 5.2.6 on 2025-12-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='laptops',
            field=models.JSONField(blank=True, default=list, verbose_name='선택된 노트북 ID들'),
        ),
    ]
